dist: trusty
language: java

cache:
  directories:
  - $HOME/.m2
  - $HOME/.mvn/

# jdk6 requires workarounds https://github.com/travis-ci/travis-ci/issues/9713
addons:
  apt:
    packages:
      - openjdk-6-jdk

before_install:
  - > # install mvn 3.2.5 for use with java6
      which $HOME/.mvn/3.2.5/bin/mvn || mkdir -p $HOME/.mvn/3.2.5 &&
      curl https://apache.osuosl.org/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz |
      tar xz -C $HOME/.mvn/3.2.5 --strip-components=1
  - if [ "$TRAVIS_JDK_VERSION" == "openjdk6" ]; then jdk_switcher use openjdk6; fi
  - mvn -v

after_script:
  - > # print more detailed info about test results
      cat target/surefire-reports/TEST-ysoserial.test.payloads.PayloadsTest.xml |
      grep testcase -A1 | grep -B1 -E 'failure|error|skipped' | grep -v -- --

matrix:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk11
    - jdk: openjdk6
    - jdk: openjdk7
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
  include:
    #- jdk: oraclejdk7 #https://github.com/travis-ci/travis-ci/issues/7884
    - jdk: oraclejdk8
    - jdk: oraclejdk11
    - jdk: openjdk6
      env: PATH=$HOME/.mvn/3.2.5/bin:$PATH
    - jdk: openjdk7
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11


